//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSalary
    {
        public int id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> SalaryMonth { get; set; }
        public Nullable<int> SalaryYear { get; set; }
    }
}
